#ifndef MMU_H
#define MMU_H

#ifndef EARLY_HEAP_SIZE
#define EARLY_HEAP_SIZE 4096
#endif

#define KERNEL_PHYSICAL_BASE 0x100000
#define KERNEL_VIRTUAL_BASE 0xC0100000
#define PAGE_SIZE 4096


#ifdef __ASSEMBLER__

#define VIRTUAL_TO_PHYSICAL(x) (x - (KERNEL_VIRTUAL_BASE - KERNEL_PHYSICAL_BASE))
#define PHYSICAL_TO_VIRTUAL(x) (x + (KERNEL_VIRTUAL_BASE - KERNEL_PHYSICAL_BASE))

#else

#define VIRTUAL_TO_PHYSICAL(x) ((uint32_t)(x) - (KERNEL_VIRTUAL_BASE - KERNEL_PHYSICAL_BASE))
#define PHYSICAL_TO_VIRTUAL(x) ((uint32_t)(x) + (KERNEL_VIRTUAL_BASE - KERNEL_PHYSICAL_BASE))

#endif /** __ASSEMBLER__ */

#endif /** MMU_H */
